### ISSUE TITLE
Removing leftover data doesn't work

### ISSUE THREAD

**Issue by K0-RR** [flattool/warehouse#172]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

gio: file:///home/k0rr/.var/app/eu.betterbird.Betterbird: Trash portal failed on /home/k0rr/.var/app/eu.betterbird.Betterbird

**Comment by ACR-Jeff** [comment]
I'm having the same issue, I've even made sure through Flatseal that I've given warehouse permissions for the directory, Still results in failure.

**Comment by ACR-Jeff** [comment]
Ok solved my problem. Make sure you have both xdg-desktop-portal and xdg-desktop-portal-gtk installed in your system (Not flatpak).
Thanks to this comment, 
https://github.com/flatpak/flatpak/issues/2446#issuecomment-448618648

**Comment by danielbmeireles** [comment]
I am facing this issue even with the xdg* packages installed in my system:

```
gio: file:///home/daniel/.var/app/org.kde.kblocks: Trash portal failed on /home/daniel/.var/app/org.kde.kblocks
```

I have the `gio` binary installed. On GNOME, I have no issues (my current system is Kubuntu 26.04 LTS).

**Comment by Yok0ri** [comment]
Same here, both xdg portals installed, Arch Linux KDE Plasma 6.6.4

**Comment by chrostino** [comment]
I am having this issue on Fedora 43 (Gnome), can't trash data of neither installed or uninstalled apps.
Just to note, I believe [bazaar](https://github.com/bazaar-org/bazaar) is also having this issue, but [flatsweep](https://github.com/giantpinkrobots/flatsweep) is not

**Comment by ro62t2** [comment]
[flatsweep uses shutil.rmtree](https://github.com/giantpinkrobots/flatsweep/blob/main/src/main.py#L515) in Python, so doesn't use the Trash.

https://github.com/bazaar-org/bazaar/issues/1481

**Comment by SleepingPanda** [comment]
Issue also occurs on Fedora 44 (Kinoite)

**Comment by RasoolSaeedNejad** [comment]
> I am facing this issue even with the xdg* packages installed in my system:
> 
> ```
> gio: file:///home/daniel/.var/app/org.kde.kblocks: Trash portal failed on /home/daniel/.var/app/org.kde.kblocks
> ```
> 
> I have the `gio` binary installed. On GNOME, I have no issues (my current system is Kubuntu 26.04 LTS).

This problem has recently resurfaced on OpenSUSE Tumbleweed and GNOME 50.

in the snapshot section, nothing can be deleted
and it shows the same error

**Comment by MaravicMarko** [comment]
I have the same issue, but I found it out while trying to restore the snapshot.

When using Warehouse to delete a Flatpak app's user data (via the trash button, or as part of snapshot restore), the operation fails with a Trash portal error. The snapshot restore itself succeeds if the target directory is manually moved out of the way first; the failure is isolated to the `gio trash` call on `~/.var/app/<app-id>/`.

## Environment

OS: Fedora 44 KDE
Warehouse v2.2.0 : installed via Flatpak (Flathub)
Portal packages:
  xdg-desktop-portal-1.22.0-1.fc44.x86_64
  xdg-desktop-portal-kde-6.6.5-1.fc44.x86_64
  xdg-desktop-portal-gtk-1.15.3-3.fc44.x86_64

## Steps to reproduce

1. Open Warehouse
2. Select any installed Flatpak app
3. Attempt to delete the app's user data, or restore a snapshot (which tries to trash the existing data directory first)

## Expected behavior

The app's data directory at `~/.var/app/<app-id>/` is moved to trash and the operation completes.

## Actual behavior

The operation fails with:

`gio: file:///home/marko/.var/app/info.febvre.Komikku: Trash portal failed on /home/marko/.var/app/info.febvre.Komikku`

Full traceback from terminal:

```
Could not trash data
gio: file:///home/marko/.var/app/info.febvre.Komikku: Trash portal failed on /home/marko/.var/app/info.febvre.Komikku
Traceback (most recent call last):
  File "/app/share/warehouse/src/snapshot_page/tar_worker.py", line 44, in extract_thread
    subprocess.run(
    ["gio", "trash", self.new_path], capture_output=True, check=True
    )
subprocess.CalledProcessError: Command '['gio', 'trash', '/home/marko/.var/app/info.febvre.Komikku/']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

  File "/app/share/warehouse/src/snapshot_page/tar_worker.py", line 61, in extract_thread
    self.do_cancel(cpe.stderr.decode())
  File "/app/share/warehouse/src/snapshot_page/tar_worker.py", line 71, in do_cancel
    self.process.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

  File "/app/share/warehouse/src/snapshot_page/tar_worker.py", line 89, in check_size
    self.fraction = working_total / self.total
ZeroDivisionError: float division by zero
```

## Investigation notes

- `gio trash ~/some-file` works correctly from the host (outside any sandbox); the file lands in `~/.local/share/Trash/files/` as expected.
- `xdg-desktop-portal` is running and healthy (`systemctl --user status xdg-desktop-portal` shows active/running).
- No trash portal errors appear in `journalctl --user -u xdg-desktop-portal` when the failure occurs, suggesting the sandboxed `gio` is not reaching the portal at all.
- `xdg-desktop-portal-kde` is installed but does not have an active systemd user unit (it is D-Bus activated on demand).
- Both `xdg-desktop-portal-kde` and `xdg-desktop-portal-gtk` are installed; a `portals.conf` preferring `kde` was added at `~/.config/xdg-desktop-portal/portals.conf` with no effect on this issue.
- The same Komikku snapshot restore worked on Linux Mint 22.3

## Workaround

Manually move the app data directory out of the way before triggering a snapshot restore.

**Comment by vincemd22** [comment]
Confirming the same issue.

**Environment**
- OS: NixOS
- DE: GNOME
- Bazaar version: 0.9.4 (vcs=48f93f4)
- Portals active: `xdg-desktop-portal-gnome`, `xdg-desktop-portal-gtk`

**Error**

failed to trash directory '/home/guybrush/.var/app/org.gnome.SoundRecorder': Trash portal failed on /home/user/.var/app/org.gnome.SoundRecorder


**Findings**
- `gio trash` on the exact same path works fine from the host, outside any sandbox.
- Same as @MaravicMarko: no errors in `journalctl --user -u xdg-desktop-portal` when Bazaar's cleanup fails — the call doesn't seem to reach the portal at all.
- Tested `flatpak override --user --filesystem=home io.github.kolunmi.Bazaar` as a workaround: no effect, so it's not a filesystem permission scoping issue on `~/.var/app`.
